### ISSUE TITLE
Chinese nickname parsed wrong

### ISSUE THREAD

**Issue by axiangcoding** [Warthunder-Open-Source-Foundation/wt_blk#15]
Using `wt-blk-pybindings = "^0.1.4"`
Expecting `33号机`, got `33�Ż�`
Clan tag also display in `��DouYa��`, could be encoding problem?

**Comment by FlareFlo** [comment]
please link the binary file parsed for debugging

**Comment by axiangcoding** [comment]
> please link the binary file parsed for debugging

Sorry, my mistake, nothing wrong from binary, it's my code problem. close the issue. Thanks
